# Generated by Django 4.1.2 on 2023-05-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicinedata',
            name='company',
            field=models.CharField(default='Cipla', max_length=100),
        ),
        migrations.AlterField(
            model_name='medicinedata',
            name='medicine_add_date',
            field=models.DateField(auto_now=True),
        ),
    ]
