# Generated by Django 4.1.2 on 2023-06-01 04:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_store', '0002_medicinedata_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinedata',
            name='medicine_add_date',
            field=models.DateField(default=datetime.date(2023, 6, 1)),
        ),
    ]
